
version: '2'
services:

  postgiscollec:
    #RASPBERRY PI
    build:
      context: https://github.com/jancelin/docker-collec.git#master:/db
      dockerfile: Dockerfile.raspberry
    #PC
    #image: jancelin/docker-collec:postgisCollec
    restart: always
#    ports:
#     - "5433:5432"
    expose:
      - 5432
    volumes:
     - "/home/pi/collec/postgres_data_collec_auto:/var/lib/postgresql"

  collec:
    #RASPBERRY PI
    build:
      container_name: collec
      context: https://github.com/jancelin/docker-collec.git#master:/build
      dockerfile: Dockerfile.rpi_collec
      args:
        - ZIP=develop.zip
        - REP=collec-develop
    #PC
    #image: jancelin/docker-collec:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - postgiscollec:postgiscollec

# Collec est accessible à cette adresse après 2 minutes (construction de la base de donnée):
#                   https://mon_ip/collec-feature_metadata

# Login: admindemo
# Password: admin_007
