version: '2'
services:
     
  postgiscollec:
    #RASPBERRY PI
    build: 
      context: https://github.com/jancelin/docker-collec.git#master:/collec/db
      dockerfile: DockerfileRaspberry
    #PC
    #build: https://github.com/jancelin/docker-collec.git#master:/collec/db -f Dockerfile
    restart: always
#    ports:
#     - "5433:5432"
    expose:
      - 5432
    volumes:
     - "/home/pi/collec/postgres_data_collec_auto:/var/lib/postgresql"
       
  collec:
    #RASPBERRY PI
    image: jancelin/geopoppy:collec-0.3
    #build: https://github.com/jancelin/geo-poppy.git#master:/collec/build -f Dockerfile.raspberry
    #PC
    #image: jancelin/docker-collec:latest
    #build: https://github.com/jancelin/geo-poppy.git#master:/collec/build -f Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - postgiscollec:postgiscollec
      
# Collec est accessible à cette adresse après 2 minutes (construction de la base de donnée):
#                   https://mon_ip/collec-feature_metadata

# Login: admindemo
# Password: admin_007
