version: '2'
services:
     
  postgiscollec:
    #image: jancelin/geopoppy:postgiscollec-0.3
    build: https://github.com/jancelin/geo-poppy.git#master:/collec/db
    restart: always
#    ports:
#     - "5433:5432"
    expose:
      - 5432
    volumes:
     - "/home/pi/collec/postgres_data_collec_auto:/var/lib/postgresql"
       
  collec:
    image: jancelin/geopoppy:collec-0.3
    #build: https://github.com/jancelin/geo-poppy.git#master:/collec/build
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - postgiscollec:postgiscollec
      
# Collec est accessible à cette adresse après 2 minutes (construction de la base de donnée):
#                   https://mon_ip/collec-feature_metadata

# Login: admindemo
# Password: admin_007
