FROM jancelin/geopoppy:postgis

MAINTAINER  Julien Ancelin - Christine Plumejeaud \
            db test for IRSTEA/Collec 

ADD start-postgis.sh /start-postgis.sh
ADD collec11.sql /collec.sql
RUN chmod 0755 /start-postgis.sh

CMD /start-postgis.sh

