version: '3'
services:
  collec-db:
    image: collec-science/docker-collec:postgisCollec
    restart: always
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/9.6/main
      - ALLOW_IP_RANGE=0.0.0.0/0
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/9.6/main

  collec-web:
    image: collec-science/docker-collec:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 632:631
    links:
      - collec-db:collec-db
volumes:
  pgdata:

# Collec est accessible à cette adresse après 2 minutes (construction de la base de donnée):
#                   https://mon_ip/collec-master
# mon_ip = 127.0.0.1, ou 172.24.1.1, et accepter l'erreur sur le certificat (ajouter aux exceptions)

# Login: admin
# Password: password
